### ISSUE TITLE
can't install default theme

### ISSUE THREAD

**Issue by chichicuervo** [superdesk/web-publisher#766]
following the guide... when I do this:

```
sudo -u www-data SYMFONY_ENV=prod php app/console swp:theme:install 7wde3e src/SWP/Bundle/FixturesBundle/Resources/themes/DefaultTheme/ -f --activate -p
```

i get this:

```
Theme could not be installed, files are reverted to previous version!
Error message: Error in one or more bulk request actions:

index: /swp_index/package/2 caused Rejecting mapping update to [swp_index] as the final mapping would have more than 1 type: [package, article]
```

and when I do this:

```
sudo -u www-data php app/console swp:theme:install 7wde3e src/SWP/Bundle/FixturesBundle/Resources/themes/DefaultTheme/ -f --activate -p
```

I get this:

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineFixturesBundle" from namespace "Doctrine\Bundle\FixturesBundle".
Did you forget a "use" statement for another namespace? in /var/www/publisher/app/AppKernel.php:19
Stack trace:
#0 /var/www/publisher/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(488): AppKernel->registerBundles()
#1 /var/www/publisher/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(132): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /var/www/publisher/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(64): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/publisher/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/publisher/app/console(30): Symfony\Component in /var/www/publisher/app/AppKernel.php on line 19
```

how to resolve?  I'm working the latest master as of Mar 26 2019.

**Comment by takeit** [comment]
Hi @chichicuervo 

please use 1.5 branch. The master branch is work in progress.

**Comment by ahilles107** [comment]
+ `Attempted to load class "DoctrineFixturesBundle" ` means that You run comamnd in `dev` env withiut composer `dev` dependencies installed. If You do this on production instance then make sure you add `--env=prod` to command or if you work on dev instance then run `composer install --dev`

**Comment by chichicuervo** [comment]
> Hi @chichicuervo
> 
> please use 1.5 branch. The master branch is work in progress.

I just checked.... my initial report was wrong about the branch... the correct branch is 'origin/1.5'

again.. i'm just following the instructions
